### ISSUE TITLE
Default filters do not analyse anything

### ISSUE THREAD

**Issue by rsking-mondo** [danielpalme/ReportGenerator-GitHub-Action#1]
When not specifying the \*filters values, this causes the filters to be '+', which excludes everything. This should either pass through the default of '+*' or not add those to the command line.

**Comment by DrifterApps** [comment]
I concur, I've been trying to figure out why I couldn't get it to work on Actions.

Came across this issue and tried your workaround and it finally works.

**Comment by danielpalme** [comment]
Thanks for reporting this issue.
It's fixed with release 4.5.7

**Comment by DrifterApps** [comment]
I tested it and it works great. Thanks
