### ISSUE TITLE
make toolpath configurable

### ISSUE THREAD

**Issue by f2calv** [danielpalme/ReportGenerator-GitHub-Action#10]
Firstly a great tool and a great extension thanks!

...but it would be great to configure the path to which the dotnet tool was installed as when using publishing NuGets in my own CI pipeline my (admittedly lazy) globbing picks up the recently installed `dotnet-reportgenerator-globaltool.4.5.6.nupkg` package and attempts to re-publish that also (which of course correctly errors).

![image](https://user-images.githubusercontent.com/16097639/118585987-3eb79f80-b79a-11eb-82a6-e7ef9e55b4e7.png)

**Comment by danielpalme** [comment]
Thanks for your PR. I will have a look within the next days.
