### ISSUE TITLE
Show badge on GitHub

### ISSUE THREAD

**Issue by mu88** [danielpalme/ReportGenerator-GitHub-Action#13]
Hi Daniel,

Thank you for your awesome tool!

I'm using your GitHub Action to create a code coverage badge and generate a GitHub artifact ([see here](https://github.com/mu88/BlazorFotoManager/actions/runs/1298496839)). Is it somehow possible to publish this badge on my corresponding [`README.md`](https://github.com/mu88/BlazorFotoManager/blob/main/README.md)? I've no clue how to reference the badge with the ZIP file of the artifact...

Thank you and best regards!

**Comment by danielpalme** [comment]
I guess that's not possible.
You should be able to upload the file to an external service (e.g. via FTP) and link the badge from there.

**Comment by mu88** [comment]
Okay thank you
