### ISSUE TITLE
Update action to use Node 16

### ISSUE THREAD

**Issue by leedsalex** [danielpalme/ReportGenerator-GitHub-Action#15]
The action currently uses version 12 of Node, which is being [deprecated by GitHub ](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) because it has been out of support since April 2022. Please update this action to use version 16 of Node.

**Comment by danielpalme** [comment]
@leedsalex 
Thanks for reporting this. I wasn't aware of the deprecation.

I already made the necessary changes in the code base. Will publish a new version as soon as possible.

**Comment by leedsalex** [comment]
Thank you, appreciate it!

**Comment by danielpalme** [comment]
Version 5.1.11 is now available. This version uses Node 16.
