### ISSUE TITLE
Failed to download action

### ISSUE THREAD

**Issue by AlexNDRmac** [danielpalme/ReportGenerator-GitHub-Action#2]
I've got error when follow your readme example:

```bash
Download action repository 'danielpalme/ReportGenerator-GitHub-Action@v4.5.7'
##[warning]Failed to download action 'https://api.github.com/repos/danielpalme/ReportGenerator-GitHub-Action/tarball/v4.5.7'. Error Response status code does not indicate success: 404 (Not Found).
```

In README you have a sample with usage.

This **uses** declaration
`uses: danielpalme/ReportGenerator-GitHub-Action@v4.5.7`
should be without **v**
`uses: danielpalme/ReportGenerator-GitHub-Action@4.5.7`

**Comment by danielpalme** [comment]
I fixed that. Thanks.
