### ISSUE TITLE
Do not show empty folders if all files have been filtered out

### ISSUE THREAD

**Issue by tbutler-qontigo** [danielpalme/ReportGenerator-GitHub-Action#20]
Hi

Using v5.3.6 of the action.

I want to exclude python test files and `__init__.py` files from scanning so I have set this:
`filefilters: "-**/__init__.py;-**/test_*.py"`

This is excluding the files but the test folders are still showing even though there is nothing to see:
![image](https://github.com/danielpalme/ReportGenerator-GitHub-Action/assets/72974415/71492e3b-093b-4f0e-bf6b-9ee03399cb70)

In this case the app/tests folder contains only two files:
* `test_main.py`
* `__init__.py`

And since both are excluded, I would expect not to see the folder in the output

thanks

**Comment by danielpalme** [comment]
I changed the implementation. Empty modules/assemblies are now excluded in the reports: https://github.com/danielpalme/ReportGenerator/commit/6c8a5e847aadfddb9cea454c46a9c55b2a4f96b7

Next release will contain this change.

**Comment by danielpalme** [comment]
New release 5.3.7 is now available.
