### ISSUE TITLE
Unable to resolve action `danielpalme/reportgenerator-github-action@5`

### ISSUE THREAD

**Issue by baksetercx** [danielpalme/ReportGenerator-GitHub-Action#21]
```
Error: Unable to resolve action `danielpalme/reportgenerator-github-action@5`, the provided ref `5` is the shortened version of a commit SHA, which is not supported. Please use the full commit SHA `5808021ec4deecb0ab3da051d49b4ce65fcc20af` instead.
```

Action suddenly started failing today, probably due to version 5.3.8. It seems the shortened SHA of the commit in release 5.3.8 (and release 5) also starts with a 5, and this confuses GitHub? I don't know if this could be resolved by using e.g. `v5` instead.

Example: https://github.com/3lvia/core-github-actions-templates/actions/runs/9953435568/job/27496886899

**Comment by josephearl** [comment]
I'd suggest starting the tag names with a `v` (e.g. `v5`) to avoid this issue

**Comment by danielpalme** [comment]
@josephearl 
Good idea. I just created a v5 tag.
