### ISSUE TITLE
Question: how to obtain the coverage binary file

### ISSUE THREAD

**Issue by ArchieCoder** [danielpalme/ReportGenerator-GitHub-Action#6]
Hello,

When I run the following command, I can only specify a result directory as follow

vstest.console Tests.dll /Enablecodecoverage /ResultsDirectory:E:\Results

However, the generated file goes under a GUID generated folder name

![image](https://user-images.githubusercontent.com/1608424/101697072-200fe880-3a45-11eb-8421-751384e15409.png)

I need to use the tool CodeCoverage.exe in order to convert the binary format to xml.

How can I obtain the folder/file with a GitHub Action workflow in order to use your ReportGenerator action? FYI, I use microsoft/setup-msbuild@v1.0.2

Thank you

**Comment by danielpalme** [comment]
In general you can use wildcards in the path. E.g.
reports: 'E:\Results\*\sebas*.coverage'

I'm not sure what the `*.coverage` file contains. Is it an XML format?
If not, you may have to [convert it first](https://github.com/danielpalme/ReportGenerator/wiki/Visual-Studio-Coverage-Tools).
Or you use another tool like [coverlet](https://github.com/coverlet-coverage/coverlet).

**Comment by ArchieCoder** [comment]
Interesting, the new version of Microsoft.VisualStudio.CodeAnalysis does not contain the classes used in your snipet. This would have been great!

![image](https://user-images.githubusercontent.com/1608424/101788367-02d32c80-3ace-11eb-9c33-fa1c94ba0b5b.png)

**Comment by danielpalme** [comment]
You should be able to use an older version!
