### ISSUE TITLE
Failed to retrieve information about 'dotnet-reportgenerator-globaltool' from remote source 

### ISSUE THREAD

**Issue by chenghuang-mdsol** [danielpalme/ReportGenerator-GitHub-Action#8]
**Description**
When a custom nuget source is configured and it doesn't contain reportgenerator tool, installation fails

**To Reproduce**
1. Add a custom Nuget source
2. Try to use the action to convert/generate any reports

**Console**
```
Failed to retrieve information about 'dotnet-reportgenerator-globaltool' from remote source 
'https://xxxxx.jfrog.io/artifactory/api/nuget/v3/nuget-local/archive/FindPackagesById()?id='dotnet-reportgenerator-globaltool'&semVerLevel=2.0.0'.
```

**Suggested Fix**
Add ```--ignore-failed-sources```
e.g.
dotnet tool update --global dotnet-reportgenerator-globaltool --ignore-failed-sources

See https://github.com/dotnet/sdk/issues/9886#issuecomment-433472367

**Comment by danielpalme** [comment]
If I add `--ignore-failed-sources` the installation won't fail.
But execution will fail, since the tool won't be available? Correct?

**Comment by chenghuang-mdsol** [comment]
> If I add `--ignore-failed-sources` the installation won't fail.
> But execution will fail, since the tool won't be available? Correct?

You get a warning, but the tool will download from official nuget source. 
It will do search from all sources instead of one.

But please try.

**Comment by danielpalme** [comment]
I added the command line switch.
