### ISSUE TITLE
Using latest version

### ISSUE THREAD

**Issue by eduherminio** [danielpalme/ReportGenerator-GitHub-Action#9]
I've unsuccessfully tried to setup my tasks to use 4.8.x versions, to avoid worrying about bumping the version number myself.
I couldn't find clear documentation about this, but as [suggested here](https://github.community/t/versioning-guidance-for-authoring-and-consuming-actions/138763), I tried:

* `danielpalme/ReportGenerator-GitHub-Action@4.8`
* `danielpalme/ReportGenerator-GitHub-Action@4`

I guess it doesn't work because it tries to match git tags in the repository.

Are you aware of any way of setting it up not having to worry about bumping the patches versions?
Despite using @dependabot, there're a bunch of PRs to approve every time a new version is released 😅

**Comment by danielpalme** [comment]
I was not able to find any documentation regarding this issue.
I guess you have to specify the full version.

**Comment by eduherminio** [comment]
I've looked further into this topic recently and it appears to depend only on git tags and branch names.
All the actions I use under https://github.com/actions have a vN tag acting as vN.x.
I've seen some others (such as [rlespinasse/github-slug-action](https://github.com/rlespinasse/github-slug-action/tree/v3.x)) combining traditional releases with branch names.

Anyway, now with @dependabot it's not a big deal, just clicking a few buttons in multiple repos.

**Comment by eduherminio** [comment]
Hi @danielpalme,

Any chance you can have another look at this issue one of these days and review the tagging strategy?
I found more info/formal recommendations about it [here](https://docs.github.com/en/actions/creating-actions/releasing-and-maintaining-actions):
> We recommend creating releases using semantically versioned tags – for example, v1.1.3 – and keeping major (v1) and minor (v1.1) tags current to the latest appropriate commit. For more information, see "[About custom actions](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions)" and "[About semantic versioning](https://docs.npmjs.com/about-semantic-versioning).

I'm asking because of this 😅the more repos I use the action on, the more time consuming it becomes to bump minor versions + especially noise

![image](https://user-images.githubusercontent.com/11148519/169248786-29b6e6fc-acbb-4119-8b00-5ec93ef5fbdb.png)

**Comment by danielpalme** [comment]
I just created a new tag named [5](https://github.com/danielpalme/ReportGenerator-GitHub-Action/releases/tag/5).

Maybe you can try to change your action to:
```
uses: danielpalme/ReportGenerator-GitHub-Action@5
```

Does this work for you?

**Comment by eduherminio** [comment]
That sounds perfect to me, thanks, but I understand it can be a pain to maintain on your side.
You can probably try to figure out an internal action that, on release, moves automatically that tag to point to the release's tag.

**Comment by danielpalme** [comment]
I aware of this, but I will definitely automate that.

**Comment by eduherminio** [comment]
@danielpalme Kind reminder v5 tag isn't being updated to the latest one, in case you're not aware.
